### ISSUE TITLE
Support for Illustator CC 2015

### ISSUE THREAD

**Issue by zopyx** [newsdev/ai2html#33]
Is it possible to use the script in CC 2015?
I installed the script, found it inside the scripts folder but it does not produce any output.

**Comment by archietse** [comment]
Make sure you restart Illustrator after putting the script in the scripts folder.

If that doesn't work, it may be because you were trying out the script on the sample files. There are a few settings that we left on the sample files that redirected the output to the parent-parent folder. I haven't had a chance to fix this yet.

You can try it again with a sample file by deleting the "ai2html-settings" text block to the left of all of the artboards. This will force the script to generate a clean settings text block which will put the output in the expected location.

I've been using the script with CC 2015 for a little while and it seems to be working as expected.

**Comment by ryanbmarx** [comment]
I'm having a similar issue (AI 2015.3). No output. It will place the config block every time, but produces no output. Have redownloaded (0.61) and restarted.

**Comment by arm5077** [comment]
A note for those finding this through Google — I had the same problem after installing ai2html on a new laptop and Illustrator version, and realized Illustrator had set the Document Color Mode to CYMK by default. Switching it over to RGB did the trick.

**Comment by ryanbmarx** [comment]
Thanks @arm5077 ... previous versions used to provide an alert for this situation. I wonder why that's no longer the case.

**Comment by mbloch** [comment]
I see that a bug was introduced in March 2016 that prevented alert box messages from displaying for non-NYTimes users... whoops! It's fixed in the current ai2html-beta.js, which will be released soon as v0.64.
